// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuhVCFV0m6x9wtrPu1I3pFE0WN9xPtBfE',
    appId: '1:985763420397:web:fe98e1742ef550253094e4',
    messagingSenderId: '985763420397',
    projectId: 'chat-app212',
    authDomain: 'chat-app212.firebaseapp.com',
    databaseURL: 'https://chat-app212-default-rtdb.firebaseio.com/',
    storageBucket: 'chat-app212.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAMhV5S47XAWlf5KuwbnGuZayZlz2YqB0',
    appId: '1:985763420397:android:8fdc935f376397093094e4',
    messagingSenderId: '985763420397',
    projectId: 'chat-app212',
    databaseURL: 'https://chat-app212-default-rtdb.firebaseio.com/',
    storageBucket: 'chat-app212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoTRVN5r3v_jI0_tC1Et2LDhMi_HfewKE',
    appId: '1:985763420397:ios:8af48501a48823613094e4',
    messagingSenderId: '985763420397',
    databaseURL: 'https://chat-app212-default-rtdb.firebaseio.com/',
    projectId: 'chat-app212',
    storageBucket: 'chat-app212.appspot.com',
    iosBundleId: 'com.flux.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoTRVN5r3v_jI0_tC1Et2LDhMi_HfewKE',
    appId: '1:985763420397:ios:e3bb22d8942c1cee3094e4',
    messagingSenderId: '985763420397',
    projectId: 'chat-app212',
    storageBucket: 'chat-app212.appspot.com',
    iosBundleId: 'com.flux.chatapp.RunnerTests',
  );
}
